- hosts: development_nodes
  vars:
    http_port: 80
    max_clients: 200
  remote_user: centos
  become: yes
  become_method: sudo
  tasks:
  - name: update yum
    command: yum -y update 
  - name: make sure we have latest yum utilities
    yum:
      name: yum-utils
      state: present
  - name: make sure we have latest device mapper persistent data
    yum:
      name: device-mapper-persistent-data
      state: present
  - name: make sure we have lvm2
    yum:
      name: lvm2
      state: present
  - name: make sure we have git
    yum:
      name: git
      state: present
  - name: make sure we have epel
    yum:
      name: epel-release
      state: present
  - name: make sure we have pip
    yum:
      name: python-pip
      state: present
  - name: make sure we are using stable releases for docker
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - name: make sure we have docker-ce
    yum:
      name: docker-ce
      state: present
  - name: start docker ce
    command: systemctl start docker
  - name: make sure we have python boto3
    pip:
      name: boto3
  - name: make sure we have python docker
    pip:
      name: docker
  - name: remove the repository if exists
    file: path=/root/wolfbeacon-core-api state=absent
  - name: clone the wolfbeacon core api
    command: git clone https://github.com/wolfbeacon/wolfbeacon-core-api.git /root/wolfbeacon-core-api
  - name: clone the settings.py file
    aws_s3:
      bucket: wolfbeacon.secret.bucket
      object: settings.py
      dest: /root/wolfbeacon-core-api/wolfbeacon/settings.py
      mode: get
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
  - name: build the docker image
    command: docker build -t wolfbeacon-core-api --no-cache .
    args:
      chdir: /root/wolfbeacon-core-api
  - name: kill all docker images
    shell: |
      if [ $(docker ps -q) ]
      then
        docker kill $(docker ps -q)
      fi
  - name: remove all docker images
    shell: |
      if [ $(docker ps -a -q) ]
      then
        docker rm $(docker ps -a -q)
      fi
  - name: run the docker image
    shell: docker run -p 80:8000 -d --restart=always wolfbeacon-core-api
